services:
  daypay.api:
    image: ${DOCKER_REGISTRY-}daypay.api
    container_name: api
    build:
      context: .
      dockerfile: host/DayPay.Host/Dockerfile
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://daypay.dashboard:18889
    networks:
      - otel

  daypay.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
    networks:
      - otel
networks:
  otel:
