version: '3.8'

services:
  daypayapi:
    image: daypayapi
    build:
      context: .
      dockerfile: host/DayPay.Host/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy: 
      replicas: 2
      placement:
        constraints:
          - node.hostname != worker2
      restart_policy:
        condition: on-failure
    networks:
      - backend
    
  redis:
    image: redis:7
    deploy:
      placement:
        constraints:
          - node.hostname == worker2
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      placement:
        constraints:
          - node.hostname == worker2
    ports:
      - "9200:9200"
    networks:
      - backend
    volumes:
      - es_data:/usr/share/elasticsearch/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    deploy:
      placement:
        constraints:
          - node.hostname == worker2
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints:
          - node.hostname != worker2 

volumes:
  redis_data:
  es_data:
  sql_data:

networks:
  backend: