version: '3.8'

services:
  daypayhost:
    build:
      context: .
      dockerfile: host/DayPay.Host/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
