receivers:
  otlp:
    protocols:
      http:
      grpc:


exporters:
  elasticsearch:
    endpoints: [ "http://elasticsearch:9200" ]

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ elasticsearch ]
